### ISSUE TITLE
Unable to install git via winget configure

### ISSUE THREAD

**Issue by priyanshu92** [microsoft/winget-cli#3628]
### Brief description of your issue

I am trying to create a winget dsc file for a project and started with just installing git. However, I am consistently running into an error. I have tried to run `winget configure` multiple times and on multiple machines but it's giving the same error.

### Steps to reproduce

Create a configuration file as below:

### File

```yaml
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# Reference: https://github.com/microsoft/winget-create#building-the-client
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WingetPackage
      id: git
      directives:
        description: Install Git
        allowPrerelease: true
      settings:
        id: Git.Git
        source: winget
  configurationVersion: 0.2.0
```

Run `winget configure -f configuration.dsc.yaml`

### Expected behavior

Configuration is applied successfully and git is installed in the system.

### Error

![image](https://github.com/microsoft/winget-cli/assets/7589718/1c70b933-d3c1-48e7-8524-2b6385e5fc4a)

### Logs

```
2023-09-15 02:45:38.487 [CORE] WinGet, version [1.7.2491-preview], activity [{14F75C8B-1425-4F62-B80D-49DF51921EEF}]
2023-09-15 02:45:38.487 [CORE] OS: Windows.Desktop v10.0.22621.2283
2023-09-15 02:45:38.487 [CORE] Command line Args: winget  configure -f .config\configuration.dsc.yaml --accept-configuration-agreements
2023-09-15 02:45:38.487 [CORE] Package: Microsoft.DesktopAppInstaller v1.22.2491.0
2023-09-15 02:45:38.487 [CORE] IsCOMCall:0; Caller: winget-cli
2023-09-15 02:45:38.495 [CLI ] WinGet invoked with arguments: 'configure' '-f' '.config\configuration.dsc.yaml' '--accept-configuration-agreements'
2023-09-15 02:45:38.495 [CLI ] Found subcommand: configure
2023-09-15 02:45:38.495 [CLI ] Leaf command to execute: root:configure
2023-09-15 02:45:38.495 [CLI ] Executing command: configure
2023-09-15 02:45:59.529 [CONF] System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.Management.Configuration.Processor.Helpers.ConfigurationUnitAndResource..ctor(ConfigurationUnitInternal configurationUnitInternal, DscResourceInfoInternal dscResourceInfoInternal)
   at Microsoft.Management.Configuration.Processor.Set.ConfigurationSetProcessor.CreateUnitProcessor(ConfigurationUnit unit)
2023-09-15 02:45:59.531 [CONF] [FAIL] Microsoft.Management.Configuration.dll!00007FFC361EBF66: LogHr(1) tid(391c) 80070057 The parameter is incorrect.

2023-09-15 02:45:59.532 [CONF] [CONF] Unit Processor exception: 80070057 [The parameter is incorrect.]
2023-09-15 02:45:59.731 [CONF] Configuration unit WingetPackage[git] failed with code 0x80070057 and error message:
The parameter is incorrect.

2023-09-15 02:45:59.732 [CLI ] Terminating context: 0x8a15c005 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\ConfigurationFlow.cpp:3f1

```

### Environment

```shell
Windows Package Manager (Preview) v1.7.2491-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2283
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.2491.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by denelon** [comment]
Was this run under user context or administrator?

Git makes a determination to install in user scope or admin scope based on the current user being a member of the local administrators group. We've seen several issues related to this. Is this problem only happening for Git or is it also impacting other installs?

**Comment by msftrubengu** [comment]
@priyanshu92 that's a bug. Can you try with naming the resource WinGetPackage?

**Comment by priyanshu92** [comment]
> Was this run under user context or administrator?
Tried with both and got the same error.

>Is this problem only happening for Git or is it also impacting other installs?
Facing with Git and GitLFS.

**Comment by priyanshu92** [comment]
@msftrubengu Changing the resource name to `WinGetPackage` worked.
