### ISSUE TITLE
Index.db can't be opened in python using SQLite3

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-cli#3727]
### Brief description of your issue

* After https://github.com/microsoft/winget-cli/pull/3666 has been merged, the generated index.db from https://cdn.winget.microsoft.com/cache/source.msix can't be opened using Python's SQLite3 module.

I've built an API to get package IDs and their versions present in the repository. It uses index.db from source.msix, and forms the map by running some SQL queries.

Source code of the API: https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/api/winget-pkg-versions.py

Logs:
```
[ERROR] DatabaseError: malformed database schema (upgradecodes_map) - near "WITHOUT": syntax error
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/vc__handler__python.py", line 13, in <module>
    __vc_spec.loader.exec_module(__vc_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./api/winget-pkg-versions.py", line 18, in <module>
    cursor.execute('SELECT id, version FROM manifest')[ERROR] DatabaseError: malformed database schema (upgradecodes_map) - near "WITHOUT": syntax error
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/vc__handler__python.py", line 13, in <module>
    __vc_spec.loader.exec_module(__vc_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./api/winget-pkg-versions.py", line 18, in <module>
    cursor.execute('SELECT id, version FROM manifest')
Unknown application error occurred
Runtime.Unknown
```

### Steps to reproduce

Run the source code of the API. Please modify the directory `/tmp/` if you're running Windows, or, get index.db manually and run the code with those lines removed.

### Expected behavior

No errors should occur, and the code should work flawlessly as it had been in previous months.

### Actual behavior

* Errors started occurring after the modifications had been made in #3666.

### Environment

```shell
Running on AWS Lambda.
```

**Comment by Trenly** [comment]
After looking into this more, I'm almost certain this is an issue with your runner and not with the schema. I opened the database in DB Browser and ran the first SQL query - it ran without issue.
![image](https://github.com/microsoft/winget-cli/assets/12611259/c84ab26e-1487-433c-bf1d-5e52e743785f)

Then I installed python and ran the commands in your script manually - it ran without issue.
```
PS C:\Users\Trenly> python
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from sqlite3 import connect
>>> db = connect("C:/Users/Trenly/Downloads/Temp/index.db")
>>> cursor = db.cursor()
>>> cursor.execute('SELECT id, version FROM manifest')
<sqlite3.Cursor object at 0x0000020302D6FF10>
>>> manifests = cursor.fetchall()
>>> manifests[1]
(1, 3)
>>> manifests[100]
(11, 118)
```

**Comment by Trenly** [comment]
> Also, I can't control the environment of AWS Lambda 

You could try putting it on AWS directly instead of going through Vercel

**Comment by vedantmgoyal2009** [comment]
I can try, but the runtime environment will be the same, whether I deploy directly or through Vercel. I chose Vercel because it gives a free tier, has a much simpler interface, and doesn't require credit card details.

However, this issue also reminds me that MS had somewhere mentioned that they will also be building a REST API to query about packages. I can't find the issue comment at the time of writing this but will attach it as soon as I get it.

**Comment by stephengillie** [comment]
Vercel sounds almost like Heroku in reselling AWS services. Lambda lets you pick the runtime, but here the problem sounds like the runtime's SQLite module. If you need more control over the environment, then a container or VM might be necessary - these would let you bundle your own SQLite module. But containers are often billed as full VMs, so are rarely on free tier for long. 
- But if this is a bug with the SQLite module, shouldn't it be reported as such to the appropriate group? 
- Does this happen with ALL Python3 SQLite modules? Have you tested locally and/or in VMs?
