### ISSUE TITLE
winget configure can not locate Microsoft.WinGet.DSC\WinGetPackage

### ISSUE THREAD

**Issue by jtnord** [microsoft/winget-cli#4021]
### Brief description of your issue

winget configure can not install packages (out of the box)

### Steps to reproduce

clean windows 11 install

config as below
```
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# Reference: https://github.com/microsoft/winget-cli#building-the-client
properties:
  configurationVersion: 0.2.0
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: chrome
      directives:
        description: Install Chrome
        allowPrerelease: false
      settings:
        id: Google.Chrome
        source: winget
```

run `winget configure theconfig.yaml --logs`

### Expected behavior

chrome is installed

### Actual behavior

installation fails

```
C:\Users\admin>winget configure C:\Users\admin\Desktop\configuration.dsc.yaml --logs
Apply :: WinGetPackage [chrome]
  Install Chrome
  Module: Microsoft.WinGet.DSC
  Settings:
    id: Google.Chrome
    source: winget
You are responsible for understanding the configuration settings you are choosing to execute. Microsoft is not responsible for the configuration file you have authored or imported. This configuration may change settings in Windows, install software, change software settings (including security settings), and accept user agreements to third-party packages and services on your behalf.  By running this configuration file, you acknowledge that you understand and agree to these resources and settings. Any applications installed are licensed to you by their owners. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages or services.
Have you reviewed the configuration and would you like to proceed applying it to the system?
[Y] Yes  [N] No: Y
Apply :: WinGetPackage [chrome]
  The configuration unit could not be found.
Some of the configuration was not applied successfully.
```

logs contain

```
2024-01-03 13:40:14.943 [CORE] WinGet, version [1.6.3482], activity [{D2A682AB-B2B1-4D2B-8037-4E771D67ABD6}]
2024-01-03 13:40:14.943 [CORE] OS: Windows.Desktop v10.0.22621.2861
2024-01-03 13:40:14.943 [CORE] Command line Args: winget  configure C:\Users\admin\Desktop\configuration.dsc.yaml --logs
2024-01-03 13:40:14.943 [CORE] Package: Microsoft.DesktopAppInstaller v1.21.3482.0
2024-01-03 13:40:14.943 [CORE] IsCOMCall:0; Caller: winget-cli
2024-01-03 13:40:14.948 [CLI ] WinGet invoked with arguments: 'configure' 'C:\Users\admin\Desktop\configuration.dsc.yaml' '--logs'
2024-01-03 13:40:14.949 [CLI ] Found subcommand: configure
2024-01-03 13:40:14.949 [CLI ] Leaf command to execute: root:configure
2024-01-03 13:40:14.949 [CLI ] Executing command: configure
2024-01-03 13:40:23.291 [CONF] Microsoft.Management.Configuration.Processor.Exceptions.FindDscResourceNotFoundException: Could not find resource: WinGetPackage [Microsoft.WinGet.DSC]
   at Microsoft.Management.Configuration.Processor.Set.ConfigurationSetProcessor.PrepareUnitForProcessing(ConfigurationUnitInternal unitInternal)
   at Microsoft.Management.Configuration.Processor.Set.ConfigurationSetProcessor.CreateUnitProcessor(ConfigurationUnit unit)
2024-01-03 13:40:23.294 [CONF] [FAIL] Microsoft.Management.Configuration.dll!00007FF8182FBF76: LogHr(1) tid(46a0) 8A15C102 
2024-01-03 13:40:23.295 [CONF] [CONF] Unit Processor exception: 8a15c102 [The text associated with this error code could not be found.]
2024-01-03 13:40:23.358 [CONF] Configuration unit WinGetPackage[chrome] failed with code 0x8a15c102 and error message:
The text associated with this error code could not be found.

2024-01-03 13:40:23.364 [CLI ] Terminating context: 0x8a15c005 at C:\__w\1\s\external\pkg\src\AppInstallerCLICore\Workflows\ConfigurationFlow.cpp:3f1
```

### Environment

```shell
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2861
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by jtnord** [comment]
FWIW `%LOCALAPPDATA%\Microsoft\WinGet\Configuration\Modules`  contains
`Microsoft.Windows.Developer`, `PSDesiredStateConfiguration` and `PSDscResources` 

`Microsoft.WinGet.DSC` is suspiciously absent... (on both machines I have checked)

**Comment by jtnord** [comment]
That works, so PEBKAC here.

The initial output also now tells me the full module name `(Microsoft.WinGet.DSC by Microsoft Coroporaion [PSGallery]\nPowerShell Modeul with DSC resources related to WinGet configurations`)  

So the part before it is trying to apply is at least attempting to retrieve the library / module or some metadata about it - but it is failing late not early?  And as Such I wonder if there is a bug lurking in here somewhere?

**Comment by denelon** [comment]
It's possible. I'm also wondering if we should have a "more intelligent" message in the case where a prerelease module is available, but a "stable" module isn't.

**Comment by denelon** [comment]
I don't think it's a bug, but clearly the CLI isn't helping developers "fall into the pit of success". I'll go ahead and close this issue and I created the other one for better messaging to help in the future.
